### ISSUE TITLE
Not Loaded MDF file

### ISSUE THREAD

**Issue by anupamayerram** [jpo/aspnet-mvc-survey-tool#1]
aspnet-SurveyTool-20150504123939.mdf database file is missing under App-Data 

![image](https://cloud.githubusercontent.com/assets/16579754/12149127/f97b0c1e-b46f-11e5-8052-c4e0a473a019.png)

**Comment by jpo** [comment]
I've committed a few changes that should fix the issue. Download or checkout the most recent version and check the README for updated Getting Started instructions. Thanks!
