### ISSUE TITLE
update-packages not recognized

### ISSUE THREAD

**Issue by cmckechney** [jpo/aspnet-mvc-survey-tool#5]
Following setup instructions.. get 

PM> update-packages
update-packages : The term 'update-packages' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ update-packages
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (update-packages:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by cmckechney** [comment]
update-database is what needs to be run.

**Comment by jpo** [comment]
Fixed! Thanks for letting me know.
